### ISSUE TITLE
Not opening on Pixel 7

### ISSUE THREAD

**Issue by CAvalanche** [GlowPuff/ImperialCommander2#24]
Hi, new to forums here, so please forgive if I'm off base.

I'm trying to download the apk to my Pixel.  From my phone, I've downloaded, allowed files from Chrome, and attempted install.  I get a "App not installed as app isn't compatible with your phone" error.  Am I doing something wrong?  Thank you.

**Comment by GlowPuff** [comment]
Hello, you're probably not doing anything wrong.  

Some ideas off the top of my head:

- I realize you have the APK on the phone, but do you have enough space to actually install it?  Unfortunately, Android doesn't tell you when this is the reason for failed installs.
- Do you have the phone forced to install to external SD card?  This will cause a problem with Imperial Commander if that's the case, because I have the app set to "Force Internal" for the install location.  In the next update I'll be changing it to "Auto".

**Comment by CAvalanche** [comment]
Hello, thank you for the reply!

Yes - I have 60G available.  I'm assuming it's not a larger file than that, lol?

I honestly don't know about the APK install location; I've never installed direct from an APK before.  From the limited research I've done, there appears to be a 32 bit vs 64 bit issue with the Pixel (i.e. 32 bits aren't allowed an install, but 64 bits are) - is IC2 32 or 64?

**Comment by GlowPuff** [comment]
IC2 is compiled for ARMv7, which is 32bit.  Not sure why, but I can't compile this project for 64bit at all - that option is grayed out.

**Comment by CAvalanche** [comment]
Thanks so much for checking on this.  It sounds like I just need to look for a different device other than my Pixel then - I'll look at that route.  Appreciate it!

**Comment by GlowPuff** [comment]
No problem!  In the future I would like to take a look at this more and add 64bit support.
