### ISSUE TITLE
New untranslated strings

### ISSUE THREAD

**Issue by jph33** [GlowPuff/ImperialCommander2#38]
Hi,
I found some new untranslated fields:
- In options > Ambient
![image](https://user-images.githubusercontent.com/71392645/227523610-ea2143d4-84e1-4d02-8735-f391ceb253d2.png)
- When launching a tutorial mission in the star wars opening scene, the name of the tutorial is not translated
![image](https://user-images.githubusercontent.com/71392645/227523834-c4fa4578-18c6-4d42-a889-b4fd096d5298.png)
- During tutorial missions, the name of the tutorial is mentioned in the bottom right of the screen but it is not translated
![image](https://user-images.githubusercontent.com/71392645/227524330-7b7ce11c-f2f4-4c76-b1f8-e0f9759e6952.png)
- In the setup page of a campaign, when adding equipement and articles to the hero some words like "Cost" and "Tier" is not translated
![image](https://user-images.githubusercontent.com/71392645/227524792-c1001c72-3f72-4935-b400-ca8dec89cecc.png)
![image](https://user-images.githubusercontent.com/71392645/227524918-f7e6b34d-4f3a-49ef-b609-f4012d4414be.png)
- In the tiles list of a mission:
![image](https://user-images.githubusercontent.com/71392645/227544022-e77d0945-e381-4623-a3fb-e62b7d9d44fb.png)

**Comment by GlowPuff** [comment]
Thank you!  Fixed for the next update.

**Comment by jph33** [comment]
@GlowPuff Can you provide the new ui json fields that have to be defined in translated files please?

**Comment by GlowPuff** [comment]
Yes, I just committed the new English ui.json with the new properties.
Be aware, I'm still updating the Translator app to support these new properties.  

Here are the new fields:
"campaignJournalUC" to SagaUISetup
"medpacInfoUC" to SagaMainApp
"cannotDefeatUC" to sagaMainApp
"ambient" to UISettings
"costUC" to uiCampaign

**Comment by GlowPuff** [comment]
I committed the English ui.json again, this time with the properly capitalized values.  I also just committed the latest Translator app with support for the new properties and auto-capitalization of the properties that need it.

**Comment by jph33** [comment]
Thanks again. I don't know if it is possible but i was thinking about a use case of the saga translater. If i want to make à correction on a give file (ie ui.sjon) but in a given langage (ie. Fr) i am not able to download the fr version of a source file to just make my correction and send back the correcte file. Am i wrong that this is not actually possible ?

**Comment by GlowPuff** [comment]
The Translator app will allow you to edit any pre-existing file, but not send it back to us.  You'd have to send the file to me or Tilman directly, or submit a pull request for the file.  

All the non-mission translated files are here:
https://github.com/GlowPuff/ImperialCommander2/tree/main/ImperialCommander2/Assets/Resources/Languages
Each language has its own folder containing all the different translation files, such as ui.json.

The instructions in the Translator app explain how to open and edit an existing file.

**Comment by jph33** [comment]
Ok. On my version i was only able to select/download a source file in english and not in another langage. Perhaps i misses something... I will give a try tomorrow.
Thanks for your time
jph33 / EloFip

**Comment by GlowPuff** [comment]
Nice, thank you for the updated translation!  

That is correct, the source is always English because that is what you refer to as a guide when translating.  The English source data appears on the right, and your translation is on the left.  The English source on the right is there for reference so you know what you're translating.  Maybe I need to rename "source" to "reference" to make it more clear?  If you have an existing, non-English translated file you want to edit, it can be drag and dropped into the app on the Welcome screen to open it up, and it'll appear on the left as usual.  The English source is always on the right for your reference.  As you mentioned, all existing translations are in that link I gave.

As for the uppercase text fields, I should have mentioned that when editing an existing translation, you'll have to TAB through each field to make the uppercase "set" into the loaded data.  This is only necessary for old UI files that haven't had their data uppercased yet.  I'm glad you were able to figure it out. 🏆 This is why I had mentioned I was going to fix all the translations myself, since it isn't straightforward.  Luckily, it's only a one-time hassle. 😅

**Comment by jph33** [comment]
Hi @GlowPuff. Sorry for this t.o but i tested this "issue" and i noticed that this point is not solved:
"In the tiles list of a mission"
Because we still see "Core" in other languages than English. Perhaps it is the expected behavior.
If it is a "bug" here is another place where we can see tiles name:
![image](https://user-images.githubusercontent.com/71392645/229479719-aff261c4-9517-46b8-a790-d3460247c646.png)
And i have a question, why do we display the "technical" id of the deployment groups? Here for example:
![image](https://user-images.githubusercontent.com/71392645/229479969-a28536b0-3dbc-4002-8115-fce00f5a07fd.png)
Regards
jph33

**Comment by GlowPuff** [comment]
Hello, yes, this is expected behavior.  When displaying Tiles to place, the Tile Identifiers (Core 7A, for example) are not translated.  And the Deployment Group Identifiers (DG001, for example) are just the group ID the app uses.

**Comment by jph33** [comment]
Ok fine. Thank you for your clarification.
