### ISSUE TITLE
Program name error

### ISSUE THREAD

**Issue by jph33** [GlowPuff/ImperialCommander2#40]
Hi,
When the application file is installed/unzipped (i tested on Android and Windows), The name does not have a space character between "Commander" and "2"

**Comment by GlowPuff** [comment]
Hi, thank you!  It's normal, but I don't really have a reason for it.  😅 If you change the filename of the exe, it will not start, though.

**Comment by jph33** [comment]
Hi thanks for the update. It is more visible on Android because it is installed and the installed program name is "Imperial Commander2". This is this parameter:
![image](https://user-images.githubusercontent.com/71392645/228150952-37ede81c-b091-4df4-8c06-beb04cb9ed6d.png)

**Comment by GlowPuff** [comment]
Hello!  The problem is, that "product name" is also used as the local storage folder name for player campaigns, custom missions, and stored session data.  If I were to change that name now, the app wouldn't be able to access anyone's previous data, and they'd be expected to manually move everything over.  Because the app is OS-agnostic, the full path to this folder isn't hardcoded.  It's a special token that Unity fills in when I invoke it in the code, depending on the operating system it's running on.  On Windows, the path is "USERNAME\AppData\LocalLow\GlowPuff\Imperial Commander2" but completely different on Mac/Linux/Android.  That's why I've always just kept it as-is, unfortunately - to not cause existing players problems when upgrading the app over time.  Yes, I shot myself in the foot on this one. 😅 

However, the next update is going to be pretty big and have lots of internal changes, including new data formats, so it might be a great time to finally correct this.

**Comment by jph33** [comment]
Thanks you very much for this new clarification. everything make sense! Good luck with the future update.
