### ISSUE TITLE
klick on 2nd Monitor minimizes game on main monitor

### ISSUE THREAD

**Issue by mackay2k4** [GlowPuff/ImperialCommander2#46]
On the new Version (2.1.0) set to full-screen mode on a two monitor setup when i click on the other monitor IC2 minimizes on the main monitor.

I know i can click Alt-Enter to go to "window mode", but as i said in full-screen mode it behaves strange. The old version did not do this.

**Comment by GlowPuff** [comment]
I'm surprised the previous version didn't do this as well, since it's the default, normal behavior of Windows to minimize a fullscreen application when making the 2nd monitor active.  Clicking on your second screen swaps focus to another window, and thus the fullscreen application does not have focus anymore.

But you're in luck, there are a couple command lines that may work here:
1) "-window-mode borderless"
OR
2) "-popupwindow"

I would try option 1 first, since that puts the app into a borderless window mode, which should make it run as a fullscreen window, but without the window chrome.  Option 2 creates the window as a pop-up window, without a frame.  Possibly the same effect.

I also read something about pressing Shift+Tab before selecting the second monitor to keep it from minimizing.
