### ISSUE TITLE
Custom Hero

### ISSUE THREAD

**Issue by AlexWaka** [GlowPuff/ImperialCommander2#51]
Hello. I found a problem with custom characters. When creating a hero (the "Hero" category is selected in the editor), in the game the character does not behave like a hero, rather like an ally: he has a different icon frame and only 1 activation.
![Hero Error](https://github.com/GlowPuff/ImperialCommander2/assets/143122966/1c87cf08-5358-4f8e-8a25-ccdd5add506c)
[Arden Ru (Jedi Knight) EN.json.txt](https://github.com/GlowPuff/ImperialCommander2/files/12432255/Arden.Ru.Jedi.Knight.EN.json.txt)

**Comment by GlowPuff** [comment]
Hi, I finally got some time and this problem is fixed.  Thanks for bringing this to my attention! 👍🏻 

The blue outline color is normal because that's the color you set for this custom hero in the Character Editor.
![image](https://github.com/GlowPuff/ImperialCommander2/assets/22311140/1324d99e-035c-4d64-894d-91ed46e558d8)

**Comment by AlexWaka** [comment]
And how to make a frame the same as the other heroes?

**Comment by GlowPuff** [comment]
Check out the latest update - I added a "LightBlue" color option to the editor.  This is the same shade of blue used by the stock Heroes. 👍🏻
