### ISSUE TITLE
Installing IC2 on a Chromebook with Linux

### ISSUE THREAD

**Issue by GodSpeedCDN** [GlowPuff/ImperialCommander2#70]
Hi there!

I'm trying to install IC2 on a Chromebook using the Linux.zip file. Can someone please assist?

So far, I've downloaded the file and it's in my download folder. I also enable the Linux terminal.

I'm tryin to start the installation using the '' sudo apt install ImperialCommander2.x86_64'' command but it says it cannot locate the file

This is my first try at Linux

**Comment by GlowPuff** [comment]
This is unfamiliar territory for me, I know little about Linux, but all I can say is make sure the Linux terminal's current working directory matches the folder location of where the app file actually is.  If it's not, you'll get that error about not finding the file, since the "sudo" command is looking inside the terminal's current working directory.

For example, let's say you have the app inside the following folder: [b]~/Documents/IC2[/b]
The tilde (~/) means your home folder.
Now let's say you open the terminal and it says something like [i][b]janik@linux: ~$[/b][/i]
The terminal's working directory is saying it's working out of your home folder, but NOT the IC2 folder.  If you ran the sudo install command now, it'll say it can't find the file.  You'll first have to "cd" (change directory) into the IC2 folder, like this:
[b]cd /Documents/IC2[/b]
Now the terminal will say [i][b]janik@linux: /Documents/IC2$[/b][/i]
Now you can run your sudo command: [b][i]sudo apt install ImperialCommander2.x86_64[/i][/b]
...since the terminal's working directory now matches that of the file's actual location on your system.

If the Linux terminal is anything like the Windows terminal,  you can drag and drop the file right into the terminal window, and it'll automatically enter the entire path to the file for you.  No need to "cd" into the folder where the app is first.  So you'd type "sudo apt install ", then drag the file into the terminal and let it auto-input the full path to the file.  Then hit Enter.

Again, I'm only vaguely familiar with Linux, and I might be talking about my ears here. 🤣

**Comment by GodSpeedCDN** [comment]
Thank you so much GlowPuff. I've replied in BGG (Imperial commander 2 thread)
