### ISSUE TITLE
Ivan Talos unit unclear in Know Your Enemy

### ISSUE THREAD

**Issue by mmyang** [GlowPuff/ImperialCommander2#90]
The Ivan Talos deployment card states it has +2 Health, and the health listed on the card is 5.  It's not clear if the unit should have 7 health or if the 5 health listed already includes the +2.  Maybe a clarification could be put in the card text.

**Comment by mmyang** [comment]
I looked up the mission in my Hoth campaign book.  Since Ivan is based on an Elite Officer, it looks like the health is 5+2.  It might be useful to specify in the app in the deployment card text that Ivan is based on the Elite Officer so players have a better understanding when deploying them.

Thanks for such a wonderful app, by the way.

**Comment by Noldorion** [comment]
You're welcome!

And yes, you need to add the additional health, because it's based on threat level. I can't just simply set the health to 7 because the mission can be played at various threat levels, and the app does not support ad-hoc calculations.

I'll add a note in the wiki for this - there are various missions where that is the case.

**Comment by Noldorion** [comment]
Added a note here:

https://github.com/GlowPuff/ImperialCommander2/wiki/4.-Imperial-Activations
