### ISSUE TITLE
Looped Panic in Bespin Gambit

### ISSUE THREAD

**Issue by Cdndragoon610** [GlowPuff/ImperialCommander2#93]
During the Panic in the Streets mission, adding a point to the Panic Index results in an infinite loop of Panic events - the first event isn't cleared with the Continue button, meaning the mission cannot progress/be completed.  It just adds another Panic event, then another, etc etc.

It appears to be a bug in how the app registers the Panic actions, and how it's supposed to reset the Panic Index after the action is complete. Rather than reducing the Panic level by one, then continuing, it seems to be reducing the Panic level by one and triggering another action no matter what the new Panic level is.

**Comment by Noldorion** [comment]
Yes, there has been a problem with how events were handled in that mission. A fixed version is available, but not implemented in the app yet - it will be fixed in the next update. Until then, you can download it here:

https://github.com/GlowPuff/ImperialCommander2/blob/main/ImperialCommander2/Assets/Resources/SagaMissions/Bespin/BESPIN4.json
